### ISSUE TITLE
Invalid MAC with get_tokens.py

### ISSUE THREAD

**Issue by Pygmalion69** [rithvikvibhu/GHLocalApi#94]
Ubuntu 20.04.2 LTS. Value returned by getmac() is rejected:

```
$ python ./get_tokens.py 
Traceback (most recent call last):
  File "./get_tokens.py", line 70, in <module>
    device_id = _get_android_id()
  File "./get_tokens.py", line 49, in _get_android_id
    raise OSError("a valid MAC could not be determined."
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).
```

Returned value is 113320225457236.

**Comment by rithvikvibhu** [comment]
Huh weird. So `getmac() >> 40` must be even. If it's not, then it's probably a random number because it couldn't get the preferred value first: https://stackoverflow.com/a/58512684/1724828

Maybe we can replace:
```py
mac_int = getmac()
```
with
```py
mac_int = getmac() & ~(1<<40)
```
